### ISSUE TITLE
I can't install any other modules after installing FrameworkPatcherGO v1.2.1

### ISSUE THREAD

**Issue by 6ur9er** [changhuapeng/FrameworkPatcherGO#14]
I can't install any other modules after installing FrameworkPatcherGO v1.2.1

v1.1.1 works well

I am using KernelSU<LKM> 11874
Android14
HyperOS1.0.4.0
Redmi K50Ultra (diting)

**Comment by 6ur9er** [comment]
> Have you tried running the last optional selection during the module installation to clear boot-framework files? That's the only main difference between v1.1.1 and v1.2.1 that could possibly affect your system.

I tried both "yes" and "no". There was no difference.

And I found my WebView don't work anymore, both 1.2.1 and 1.1.1
I can only got a white screen with nothing
I am using KernelSU<LKM>11898

**Comment by changhuapeng** [comment]
It's weird that even v1.1.1 that was working well previously, started throwing problems. Have you recently installed any new modules or updated your ROM, etc, that could have maybe conflicted with FPGo? You can also try wiping your dalvik cache to see if that solves the issue.

Apart from these, I have no real solution for you because the way FPGo works is through overlaying your system framework.jar and that could cause various problems on different phones and ROMs. But if you're still insistent on using FPGo then you can read my XDA thread where there's a FAQ and also the many comments from users sharing their experiences and workarounds to some of the problems they have encountered.
