### ISSUE TITLE
How to modify keybox.java

### ISSUE THREAD

**Issue by 1310286727** [changhuapeng/FrameworkPatcherGO#2]
There is no explanation on how to modify keybox.java or android.java mentioned in the project.

**Comment by changhuapeng** [comment]
I believe that FrameworkPatcher project stated intermediate Java knowledge as part of its requirement, so it assumes user has the know-how already.

To add your fingerprint, modify this part: https://github.com/chiteroman/FrameworkPatch/blob/69e08eff494b68ccd3ec71ffb04e0a798d7c686e/app/src/main/java/com/android/internal/util/framework/Android.java#L55

To add your keybox, modify this file: https://github.com/chiteroman/FrameworkPatch/blob/69e08eff494b68ccd3ec71ffb04e0a798d7c686e/app/src/main/java/com/android/internal/util/framework/Keybox.java

If your keybox has 3 certificates instead of 2 certificates like the one used in the project, then you'll have to modify this section too, with your additional certificate: https://github.com/chiteroman/FrameworkPatch/blob/69e08eff494b68ccd3ec71ffb04e0a798d7c686e/app/src/main/java/com/android/internal/util/framework/Android.java#L67

Honestly, this is out of scope for this module so I'm going to close this issue.
