### ISSUE TITLE
Installation failed! On magisk alph

### ISSUE THREAD

**Issue by 49ronind** [changhuapeng/FrameworkPatcherGO#8]
[magisk_install_log_2024-06-14T16.26.16.log](https://github.com/user-attachments/files/15835182/magisk_install_log_2024-06-14T16.26.16.log)

[framework.jar.zip](https://github.com/user-attachments/files/15835208/framework.jar.zip)

![Screenshot_2024-06-14-16-34-46-832_io github vvb2060 magisk](https://github.com/changhuapeng/FrameworkPatcherGO/assets/88111636/563e028d-2223-4d56-8a94-f6cefe347ea3)

**Comment by changhuapeng** [comment]
I'm surprised. This is the first report of apktool failing and causing error. This module uses apktool to decompile/recompile framework.jar before/after patching so it is an essential tool and can't be bypassed. Apktool does not officially support running on Android, so to fix this issue requires modifying apktool.

Since this is the only case of apktool not working, I don't foresee solving this issue in the near future.

**Comment by changhuapeng** [comment]
Apktool has been updated in v1.1.0. Please test if it solves the error you're encountering.
